/**
 * Writes a project's `CLAUDE.md` map — the table of contents an agent reads on
 * arrival. Wave 6's precondition: until an arbitrary repo can get a map,
 * nothing downstream (rules, scan, debt register) has anything to stand on.
 *
 * `project-bootstrap.ts`'s `writeRootClaude` could not do this. It is private,
 * runs only from `bootstrapProject`, and takes template `SubstitutionVars` with
 * a hardcoded `frontend/` + `backend/` layout — so only projects Agent Office
 * scaffolded ever got a map, which is the minority of them.
 *
 * The detection it needed already existed: `project-map.ts` derives layout,
 * convention docs and run commands live for EVERY project, because that map is
 * injected into every agent's prompt today. This renders the same facts to a
 * file rather than growing a second detector that drifts from the first.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { writeFileAtomic } from "../infra/fs-atomic";
import { log } from "../infra/log";
import { clean, conventionDocs, topLevelEntries } from "./project-map";
import { detectBuildCommand, detectDevCommands, detectPackageManager } from "./project-runtime";

/**
 * Marks a file this module owns. Its absence means a human (or another tool)
 * wrote the file, and regenerating would destroy their work — the same class
 * of silent overwrite that cost a project its roster in #154.
 */
export const PROJECT_MAP_MARKER = "<!-- agent-office:project-map -->";

export type ProjectMapSkipReason = "no_cwd" | "handwritten";

export interface ProjectMapResult {
  path: string;
  /** False means nothing was written; `reason` says why. */
  written: boolean;
  reason?: ProjectMapSkipReason;
  /** Rendered content — returned even when skipped, so a caller can preview. */
  content: string;
}

/** True when `CLAUDE.md` is absent or was generated by us. */
export function isRegenerable(cwd: string): boolean {
  const path = join(cwd, "CLAUDE.md");
  if (!existsSync(path)) return true;
  try {
    return readFileSync(path, "utf8").includes(PROJECT_MAP_MARKER);
  } catch {
    return false; // unreadable — treat as precious, never overwrite blind
  }
}

/** The map body for `cwd`. Pure apart from reading the directory. */
export function renderProjectMap(name: string, cwd: string): string {
  const out: string[] = [PROJECT_MAP_MARKER, "", `# ${clean(name, 80)}`, ""];
  out.push(
    "Orientation for agents working in this repo. Generated from what is on",
    "disk — edit the sections below and they will be preserved only if you",
    "remove the marker line above.",
    "",
  );

  const dirs = topLevelEntries(cwd);
  if (dirs.length > 0) {
    out.push("## Layout", "", ...dirs.map((d) => `- \`${d}/\``), "");
  }

  const docs = conventionDocs(cwd).filter((d) => d !== "CLAUDE.md");
  if (docs.length > 0) {
    out.push("## Read before writing code", "", ...docs.map((d) => `- \`${d}\``), "");
  }

  const pm = detectPackageManager(cwd);
  const cmds: string[] = [];
  const seen = new Set<string>();
  const push = (label: string, argv: string[]) => {
    const key = argv.join(" ");
    if (seen.has(key) || cmds.length >= 6) return;
    seen.add(key);
    cmds.push(`| ${clean(label, 24)} | \`${clean(key, 120)}\` |`);
  };
  const build = detectBuildCommand(cwd, pm);
  if (build) push("build", build);
  for (const d of detectDevCommands(cwd)) push(d.name.split("·").pop()!.trim().toLowerCase(), d.argv);
  if (cmds.length > 0) {
    out.push(`## Run (${clean(pm, 24)})`, "", "| | |", "|---|---|", ...cmds, "");
  }

  return `${out.join("\n").trimEnd()}\n`;
}

/**
 * Regenerate `<project>/CLAUDE.md`.
 *
 * Refuses a hand-written file unless `force`. A map that silently replaces a
 * human's orientation doc is worse than no map: the content it destroys is
 * exactly the content it is trying to provide.
 */
export function refreshProjectMap(
  projectId: string,
  cwd: string | undefined,
  name: string,
  opts: { force?: boolean } = {},
): ProjectMapResult {
  if (!cwd || !existsSync(cwd)) {
    return { path: "", written: false, reason: "no_cwd", content: "" };
  }
  const path = join(cwd, "CLAUDE.md");
  const content = renderProjectMap(name, cwd);

  if (!opts.force && !isRegenerable(cwd)) {
    log.info("project.map_skipped", { projectId, reason: "handwritten" });
    return { path, written: false, reason: "handwritten", content };
  }

  writeFileAtomic(path, content);
  log.info("project.map_written", { projectId, path, bytes: content.length });
  return { path, written: true, content };
}
