/** Writes a project's `CLAUDE.md` map, sharing project-map.ts's detectors. */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { writeFileAtomic } from "../infra/fs-atomic";
import { log } from "../infra/log";
import { clean, conventionDocs, topLevelEntries } from "./project-map";
import { detectBuildCommand, detectDevCommands, detectPackageManager } from "./project-runtime";

/** Marks a file this module owns; its absence means a human wrote it. */
export const PROJECT_MAP_MARKER = "<!-- agent-office:project-map -->";

export type ProjectMapSkipReason = "no_cwd" | "handwritten" | "write_failed";

export interface ProjectMapResult {
  path: string;

  written: boolean;
  reason?: ProjectMapSkipReason;
  /** Returned even when skipped, so a caller can preview. */
  content: string;
}

export function isRegenerable(cwd: string): boolean {
  const path = join(cwd, "CLAUDE.md");
  if (!existsSync(path)) return true;
  try {
    // FIRST LINE only — `.includes` destroyed docs that MENTIONED the marker.
    return readFileSync(path, "utf8").split("\n", 1)[0]!.trim() === PROJECT_MAP_MARKER;
  } catch {
    return false; // unreadable — treat as precious, never overwrite blind
  }
}

/** Repo text is DATA: `|` splits a GFM cell even inside a code span. */
function cell(s: string, max: number): string {
  return clean(s, max).replace(/[|<>`]/g, " ").replace(/\s+/g, " ").trim();
}

export function renderProjectMap(name: string, cwd: string): string {
  const out: string[] = [PROJECT_MAP_MARKER, "", `# ${cell(name, 80)}`, ""];
  out.push(
    "Generated by Agent Office from what is on disk. Hand edits are",
    "overwritten; to take ownership of this file, delete the marker line above.",
    "",
  );

  const dirs = topLevelEntries(cwd);
  if (dirs.length > 0) {
    out.push("## Layout", "", ...dirs.map((d) => `- \`${d}/\``), "");
  }

  const docs = conventionDocs(cwd).filter((d) => d !== "CLAUDE.md");
  if (docs.length > 0) {
    out.push("## Read before writing code", "", ...docs.map((d) => `- \`${d}\``), "");
  }

  const pm = detectPackageManager(cwd);
  const cmds: string[] = [];
  const seen = new Set<string>();
  const push = (label: string, argv: string[]) => {
    const key = argv.join(" ");
    if (seen.has(key) || cmds.length >= 6) return;
    seen.add(key);
    cmds.push(`| ${cell(label, 24)} | \`${cell(key, 120)}\` |`);
  };
  const build = detectBuildCommand(cwd, pm);
  if (build) push("build", build);
  for (const d of detectDevCommands(cwd)) push(d.name.split("·").pop()!.trim().toLowerCase(), d.argv);
  if (cmds.length > 0) {
    out.push(`## Run (${cell(pm, 24)})`, "", "| | |", "|---|---|", ...cmds, "");
  }

  return `${out.join("\n").trimEnd()}\n`;
}

/** Regenerate `CLAUDE.md`. Refuses a hand-written file unless `force`. */
export function refreshProjectMap(
  projectId: string,
  cwd: string | undefined,
  name: string,
  opts: { force?: boolean } = {},
): ProjectMapResult {
  if (!cwd || !existsSync(cwd)) {
    return { path: "", written: false, reason: "no_cwd", content: "" };
  }
  const path = join(cwd, "CLAUDE.md");
  const content = renderProjectMap(name, cwd);

  if (!opts.force && !isRegenerable(cwd)) {
    log.info("project.map_skipped", { projectId, reason: "handwritten" });
    return { path, written: false, reason: "handwritten", content };
  }

  try {
    writeFileAtomic(path, content);
  } catch (err) {
    // A reason, not a throw: one unwritable project must not abort a scan.
    log.warn("project.map_write_failed", { projectId, path, err: String(err) });
    return { path, written: false, reason: "write_failed", content };
  }
  log.info("project.map_written", { projectId, path, bytes: content.length });
  return { path, written: true, content };
}
