/** Writes a project's `CLAUDE.md` map. The marker below is what marks the
 *  file as ours; its absence means a human wrote it, so we leave it alone. */
import { existsSync, readFileSync } from "node:fs";
import { basename, join } from "node:path";
import { writeFileAtomic } from "../infra/fs-atomic";
import { log } from "../infra/log";
import { clean, conventionDocs, topLevelEntries } from "./project-map";
import { detectBuildCommand, detectDevCommands, detectPackageManager } from "./project-runtime";

export const PROJECT_MAP_MARKER = "<!-- agent-office:project-map -->";

export type ProjectMapSkipReason = "no_cwd" | "handwritten" | "write_failed";

export interface ProjectMapResult {
  path: string;

  written: boolean;
  reason?: ProjectMapSkipReason;
  content: string;
}

export function isRegenerable(cwd: string): boolean {
  const path = join(cwd, "CLAUDE.md");
  if (!existsSync(path)) return true;
  try {
    // FIRST LINE only — `.includes` destroyed docs that MENTIONED the marker.
    return readFileSync(path, "utf8").split("\n", 1)[0]!.trim() === PROJECT_MAP_MARKER;
  } catch {
    return false; // unreadable — treat as precious, never overwrite blind
  }
}

/** GFM links these unaided, so stripping `[`/`]` does not cover a heading. */
const LINKIFIERS = [/\b[a-z][a-z0-9+.-]*:\/\//gi, /\bwww\./gi, /[\w.+-]+@[\w-]+\.[\w.-]+/g];

/** A heading is not a fence, so markup goes; `\s+` also eats U+2028/9. */
function cell(s: string, max: number): string {
  let out = clean(s, max);
  for (const re of LINKIFIERS) out = out.replace(re, " ");
  return out.replace(/[|<>`[\]]/g, " ").replace(/\s+/g, " ").trim();
}

/** A Run line, kept VERBATIM — a sanitised command is a DIFFERENT command that
 *  also runs, printed as fact. A GFM table could not offer that: see the tests. */
function runLine(s: string, max: number): string {
  return clean(s, max).replace(/\s+/g, " ").trim();
}

/** Second-line defence: rows are label-indented, so none can close the block
 *  (a closing fence allows at most 3 leading spaces) whatever this returns. */
function fenceFor(rows: string[]): string {
  const runs = rows.flatMap((r) => [...r.matchAll(/`+/g)].map((m) => m[0].length));
  return "`".repeat(Math.max(2, ...runs) + 1);
}

export function renderProjectMap(name: string, cwd: string): string {
  // A name that sanitises away entirely would emit a bare `# `.
  const title = cell(name, 80) || cell(basename(cwd), 80) || "Project";
  const out: string[] = [PROJECT_MAP_MARKER, "", `# ${title}`, ""];
  out.push(
    "Generated by Agent Office from what is on disk. Hand edits are",
    "overwritten; to take ownership of this file, delete the marker line above.",
    "",
  );

  const dirs = topLevelEntries(cwd);
  if (dirs.length > 0) {
    // Second-line defence: topLevelEntries already allowlists to [\w.@-].
    out.push("## Layout", "", ...dirs.map((d) => `- \`${cell(d, 60)}/\``), "");
  }

  const docs = conventionDocs(cwd).filter((d) => d !== "CLAUDE.md");
  if (docs.length > 0) {
    out.push("## Read before writing code", "", ...docs.map((d) => `- \`${d}\``), "");
  }

  const pm = detectPackageManager(cwd);
  const rows: string[] = [];
  const seen = new Set<string>();
  const push = (label: string, argv: string[]) => {
    const key = argv.join(" ");
    if (seen.has(key) || rows.length >= 6) return;
    seen.add(key);
    rows.push(`${runLine(label, 24).padEnd(12)} ${runLine(key, 120)}`.trimEnd());
  };
  const build = detectBuildCommand(cwd, pm);
  if (build) push("build", build);
  for (const d of detectDevCommands(cwd)) push(d.name.split("·").pop()!.trim().toLowerCase(), d.argv);
  if (rows.length > 0) {
    const fence = fenceFor(rows);
    out.push(`## Run (${cell(pm, 24)})`, "", `${fence}sh`, ...rows, fence, "");
  }

  return `${out.join("\n").trimEnd()}\n`;
}

/** Regenerate `CLAUDE.md`. Refuses a hand-written file unless `force`. */
export function refreshProjectMap(
  projectId: string,
  cwd: string | undefined,
  name: string,
  opts: { force?: boolean } = {},
): ProjectMapResult {
  if (!cwd || !existsSync(cwd)) {
    return { path: "", written: false, reason: "no_cwd", content: "" };
  }
  const path = join(cwd, "CLAUDE.md");
  const content = renderProjectMap(name, cwd);

  if (!opts.force && !isRegenerable(cwd)) {
    log.info("project.map_skipped", { projectId, reason: "handwritten" });
    return { path, written: false, reason: "handwritten", content };
  }

  try {
    writeFileAtomic(path, content);
  } catch (err) {
    // A reason, not a throw: one unwritable project must not abort a scan.
    log.warn("project.map_write_failed", { projectId, path, err: String(err) });
    return { path, written: false, reason: "write_failed", content };
  }
  log.info("project.map_written", { projectId, path, bytes: content.length });
  return { path, written: true, content };
}
