/**
 * Shell env mirror — writes the active project tab's resolved env (Claude
 * account, GitHub account, linked secrets) to a small shell script the user
 * can `source` in their own terminal. `resolveSpawnEnv` (runs/spawn-env.ts)
 * is the source of truth for what a *spawned* `claude`/`git` process gets;
 * an interactive shell can't have env injected into it from outside, so this
 * is a parallel, file-based mirror the shell re-sources on its own (see the
 * `precmd` hook installed in ~/.zshrc).
 *
 * Regenerated on every active-tab switch (ui-settings PATCH route, "tabs-state"
 * key) and once on server boot. Best-effort: never throws.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { APP_STATE_DIR, DEFAULT_ACCOUNT_ID, DEFAULT_GITHUB_ACCOUNT_ID } from "../infra/paths";
import { readProject } from "../projects/projects";
import { getUiSetting } from "../db/ui-settings";
import { log } from "../infra/log";
import * as accounts from "./accounts";
import * as githubAccounts from "./github-accounts";
import * as secrets from "./secrets";

export const SHELL_ENV_PATH = join(APP_STATE_DIR, "shell-env.sh");

// Fixed var names this file ever manages, unset up front on every regen so
// switching projects (or clearing the active tab) never leaves a stale var
// from the previous project behind. Secret names are dynamic — unioned in at
// write time from every secret ever created.
const MANAGED_VARS = [
  "AGENT_OFFICE_PROJECT",
  "AGENT_OFFICE_PROJECT_DIR",
  "CLAUDE_CONFIG_DIR",
  "GH_CONFIG_DIR",
  "GIT_CONFIG_COUNT",
  "GIT_CONFIG_KEY_0",
  "GIT_CONFIG_VALUE_0",
  "GIT_CONFIG_KEY_1",
  "GIT_CONFIG_VALUE_1",
];

function sq(v: string): string {
  return `'${v.replace(/'/g, "'\\''")}'`;
}

/** CLAUDE_CONFIG_DIR line for a non-default account id, or []. */
function accountLines(accountId: string | undefined): string[] {
  if (!accountId || accountId === DEFAULT_ACCOUNT_ID) return [];
  const account = accounts.get(accountId);
  return account ? [`export CLAUDE_CONFIG_DIR=${sq(account.configDir)}`] : [];
}

/** GH_CONFIG_DIR + credential-helper lines for a non-default github account,
 *  or [] when unset/unresolvable. Same plumbing as resolveSpawnEnv: `gh`/`git`
 *  over HTTPS both need to authenticate as this account, not whatever the OS
 *  credential store cached. Fixed indices (0/1) are safe here, unlike the
 *  spawn path, since this file always starts from a clean unset rather than
 *  appending to an inherited GIT_CONFIG_COUNT. */
function githubAccountLines(githubAccountId: string | undefined, projectId: string | null): string[] {
  if (!githubAccountId || githubAccountId === DEFAULT_GITHUB_ACCOUNT_ID) return [];
  const githubAccount = githubAccounts.get(githubAccountId);
  if (!githubAccount) {
    log.warn("shell_env.github_account_missing", { projectId, githubAccountId });
    return [];
  }
  return [
    `export GH_CONFIG_DIR=${sq(githubAccount.configDir)}`,
    "export GIT_CONFIG_COUNT=2",
    "export GIT_CONFIG_KEY_0='credential.https://github.com.helper'",
    "export GIT_CONFIG_VALUE_0=''",
    "export GIT_CONFIG_KEY_1='credential.https://github.com.helper'",
    "export GIT_CONFIG_VALUE_1='!gh auth git-credential'",
  ];
}

/** Active project id from the persisted tab strip, or null (no tabs open / not
 *  yet hydrated / malformed). */
export function activeProjectIdFromTabs(): string | null {
  const raw = getUiSetting("tabs-state");
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw) as {
      tabs?: Array<{ id: string; projectId: string }>;
      activeTabId?: string | null;
    };
    const tab = parsed.tabs?.find((t) => t.id === parsed.activeTabId);
    return tab?.projectId ?? null;
  } catch {
    return null;
  }
}

/** Regenerate `SHELL_ENV_PATH` for `projectId` (or clear it when null / the
 *  project can't be read). Owner-only permissions — secrets are written in
 *  plaintext, same trust boundary as `~/.aws/credentials`. */
export function writeActiveShellEnv(projectId: string | null): void {
  try {
    const allSecretNames = [...new Set(secrets.list().map((s) => s.name))];
    const lines: string[] = [
      "# Auto-generated by Agent Office — do not edit by hand, it's overwritten on",
      "# every project tab switch. Source from your shell rc:",
      `#   [ -f ${SHELL_ENV_PATH} ] && source ${SHELL_ENV_PATH}`,
      `unset ${[...MANAGED_VARS, ...allSecretNames].join(" ")}`,
    ];

    const project = projectId ? readProject(projectId) : null;
    if (project) {
      lines.push(`export AGENT_OFFICE_PROJECT=${sq(project.meta.name)}`);
      if (project.meta.cwd) lines.push(`export AGENT_OFFICE_PROJECT_DIR=${sq(project.meta.cwd)}`);

      lines.push(...accountLines(project.meta.accountId));
      lines.push(...githubAccountLines(project.meta.githubAccountId, projectId));

      for (const secret of secrets.listRawForProject(projectId!)) {
        lines.push(`export ${secret.name}=${sq(secret.value)}`);
      }
    }

    writeFileSync(SHELL_ENV_PATH, lines.join("\n") + "\n", { mode: 0o600 });
  } catch (err) {
    log.warn("shell_env.write_failed", { projectId, error: String(err) });
  }
}
